version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8082:80"
        volumes:
          - ./code/doma:/code
          - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        
      build: php
      volumes:
            - ./code/doma/:/code

    mariadb:
      image: mariadb:10.1
      environment:
        - MYSQL_ROOT_PASSWORD=nwik
        - MYSQL_DATABASE=doma
        - MYSQL_USER=nwik
        - MYSQL_PASSWORD=nwik
      volumes:
        - ./mariadb:/var/lib/mysql
